# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='Friends', to='friends_app.Person')),
                ('name2', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='friends_app.Person')),
            ],
        ),
    ]
