# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20170525_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinfriends',
            old_name='person1',
            new_name='person_1',
        ),
        migrations.RenameField(
            model_name='joinfriends',
            old_name='person2',
            new_name='person_2',
        ),
    ]
