# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20170524_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(max_length=45),
        ),
    ]
