# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20170524_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=145),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=145),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
