# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_date_of_birth'),
        ('quote_app', '0002_auto_20170531_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='quote_com',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_com',
            new_name='user',
        ),
        migrations.AddField(
            model_name='quotes',
            name='posted_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='username', to='login_app.User'),
            preserve_default=False,
        ),
    ]
